### ISSUE TITLE
Review and amend Developer community document

### ISSUE THREAD

**Issue by caprenter** [IATI/IATI-Developer-Documentation#18]
This page is slightly out of date:
http://iatistandard.org/developer/community-about/

**Comment by Bjwebb** [comment]
@caprenter Have you made all the changes you want to this, or is there more still to do?

**Comment by caprenter** [comment]
The commit above has been accepted, but I can see that for example the discourse forum is not mentioned, so the task remains

**Comment by hayfield** [comment]
This is now out of date again since IRC is not used and [Community Tech Calls](http://discuss.iatistandard.org/t/iati-community-tech-calls-tool-builders-and-developers/708) are now a thing.

@dalepotter is this a priority update?

**Comment by akmiller01** [comment]
Page seems roughly up to date, presently https://iatistandard.org/en/guidance/developer/community-about/
