### ISSUE TITLE
Update Proposal: A Single Source of Truth for the IATI Standard

### ISSUE THREAD

**Issue by caprenter** [IATI/IATI-Developer-Documentation#23]
There are broken links in the document (see https://github.com/IATI/IATI-Websites/issues/152 )and some information is out of date.

**Comment by Bjwebb** [comment]
@caprenter Have you made all the changes you want to this, or is there more still to do?

**Comment by caprenter** [comment]
Yes I think so. Closing this. If anyone has other issues in this document they can create a new issue. 

This ticket was partly because the ticket about broken links was in the IATI-Websites repository, but the work needed to be done here, and because in fixing the broken link I also spotted some out of date information.
