### ISSUE TITLE
More XQuery to share

### ISSUE THREAD

**Issue by caprenter** [IATI/IATI-Developer-Documentation#27]
The following XQuery shows you duplicate iati-identifiers in a group of iati-activities
 `//iati-activities/iati-activity[iati-identifier = preceding-sibling::iati-activity/iati-identifier]/iati-identifier`

and this will return the XML of those duplicates activities (it doesn't show the original tho...)
`//iati-activities/iati-activity[iati-identifier = preceding-sibling::iati-activity/iati-identifier]`

This could be added to the xquery.rst file

**Comment by hayfield** [comment]
This is a suggestion to be aware of when undertaking the review in #34

**Comment by akmiller01** [comment]
https://github.com/IATI/IATI-Developer-Documentation/pull/78
